import { Bid, PricingTier, Invoice, Competitor, CompetitorTrend, PricingStrategy, TenderPattern, CompetitorSWOT, AIInsight, StrategicRecommendation, HeadToHeadCompetition, TacticEffectiveness, CompetitorHeadToHead, WinLossInsight, TeamMember, TeamComposition, TeamPerformanceMetric, OptimalTeamRecommendation, TeamPerformanceTrend, TeamCollaboration, CollaborationPattern, TeamMemberNetworkMetrics, OptimalChemistry, CollaborationTimelineEvent, CriticalMoment, FutureCollaborationForecast } from "@/types";

export * from "./liveTracking";
export * from "./qualityMetrics";

export const MOCK_BIDS: Bid[] = [
  {
    id: "bid_001",
    title: "Digital Infrastructure Modernisation",
    authority: "Greater Manchester Combined Authority",
    deadline: "2026-04-15",
    winProbability: 87,
    complianceScore: 94,
    status: "active",
    value: 2500000,
  },
  {
    id: "bid_002",
    title: "Smart City IoT Platform Implementation",
    authority: "Birmingham City Council",
    deadline: "2026-03-28",
    winProbability: 72,
    complianceScore: 88,
    status: "active",
    value: 1850000,
  },
  {
    id: "bid_003",
    title: "Cybersecurity Framework Enhancement",
    authority: "Welsh Government",
    deadline: "2026-05-10",
    winProbability: 91,
    complianceScore: 96,
    status: "active",
    value: 3200000,
  },
  {
    id: "bid_004",
    title: "Public Services Digital Transformation",
    authority: "Scottish Government",
    deadline: "2026-03-01",
    winProbability: 65,
    complianceScore: 82,
    status: "submitted",
    value: 4100000,
  },
];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: "standard",
    name: "Standard Bidder",
    description: "Essential tools for emerging bid teams",
    monthlyPrice: 499,
    annualPrice: 4990,
    features: [
      "Up to 15 active bids",
      "Doccute PDF processing",
      "Basic compliance scoring",
      "Email support",
      "Standard templates",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise OS",
    description: "Complete intelligence platform for serious bidders",
    monthlyPrice: 1299,
    annualPrice: 12990,
    recommended: true,
    features: [
      "Unlimited active bids",
      "Advanced AI predictive scoring",
      "Full PPN 06/20 compliance engine",
      "Zero-hallucination vector search",
      "Priority support (24/7)",
      "Custom integrations",
      "Team collaboration tools",
      "Advanced analytics dashboard",
    ],
  },
  {
    id: "custom",
    name: "Custom Enterprise",
    description: "Tailored solutions for large organisations",
    monthlyPrice: 0,
    annualPrice: 0,
    features: [
      "Everything in Enterprise OS",
      "Dedicated account manager",
      "Custom AI model training",
      "White-label options",
      "On-premise deployment available",
      "Custom SLA agreements",
      "Bespoke feature development",
    ],
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv_001",
    date: "2026-02-01",
    amount: 1299,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: "inv_002",
    date: "2026-01-01",
    amount: 1299,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: "inv_003",
    date: "2025-12-01",
    amount: 1299,
    status: "paid",
    downloadUrl: "#",
  },
];

export const FEATURE_HIGHLIGHTS = [
  {
    title: "Predictive Scoring",
    description: "AI-powered win probability analysis trained on 10,000+ UK public sector contracts",
    icon: "brain",
  },
  {
    title: "Doccute PDF Pipeline",
    description: "Intelligent document chunking and extraction with zero hallucination guarantees",
    icon: "file-check",
  },
  {
    title: "PPN 06/20 Compliance",
    description: "Automated compliance verification against UK procurement policy notes",
    icon: "shield-check",
  },
];

export const MOCK_COMPETITORS: Competitor[] = [
  {
    id: "comp_001",
    name: "Capita PLC",
    size: "Major",
    specialty: ["IT Services", "Business Services", "Digital Transformation"],
    totalBids: 284,
    wins: 178,
    losses: 106,
    winRate: 62.7,
    averageBidValue: 3800000,
    marketShare: 18.5,
  },
  {
    id: "comp_002",
    name: "Fujitsu UK",
    size: "Major",
    specialty: ["IT Infrastructure", "Cloud Services", "Cybersecurity"],
    totalBids: 192,
    wins: 134,
    losses: 58,
    winRate: 69.8,
    averageBidValue: 4200000,
    marketShare: 15.2,
  },
  {
    id: "comp_003",
    name: "Sopra Steria",
    size: "Large",
    specialty: ["Digital Consulting", "Software Development", "Data Analytics"],
    totalBids: 156,
    wins: 89,
    losses: 67,
    winRate: 57.1,
    averageBidValue: 2900000,
    marketShare: 11.3,
  },
  {
    id: "comp_004",
    name: "CGI IT UK",
    size: "Major",
    specialty: ["Systems Integration", "Managed Services", "Business Consulting"],
    totalBids: 218,
    wins: 147,
    losses: 71,
    winRate: 67.4,
    averageBidValue: 3500000,
    marketShare: 14.8,
  },
  {
    id: "comp_005",
    name: "BAE Systems Digital Intelligence",
    size: "Large",
    specialty: ["Cybersecurity", "Defense IT", "Intelligence Solutions"],
    totalBids: 98,
    wins: 72,
    losses: 26,
    winRate: 73.5,
    averageBidValue: 5800000,
    marketShare: 8.9,
  },
  {
    id: "comp_006",
    name: "Atos UK",
    size: "Large",
    specialty: ["Cloud Migration", "Cybersecurity", "Digital Workplace"],
    totalBids: 167,
    wins: 94,
    losses: 73,
    winRate: 56.3,
    averageBidValue: 3100000,
    marketShare: 9.7,
  },
];

export const MOCK_COMPETITOR_TRENDS: CompetitorTrend[] = [
  // Capita PLC
  { month: "Aug 25", competitor: "Capita PLC", winRate: 58, bids: 22 },
  { month: "Sep 25", competitor: "Capita PLC", winRate: 61, bids: 24 },
  { month: "Oct 25", competitor: "Capita PLC", winRate: 59, bids: 26 },
  { month: "Nov 25", competitor: "Capita PLC", winRate: 64, bids: 23 },
  { month: "Dec 25", competitor: "Capita PLC", winRate: 67, bids: 21 },
  { month: "Jan 26", competitor: "Capita PLC", winRate: 63, bids: 25 },
  { month: "Feb 26", competitor: "Capita PLC", winRate: 65, bids: 24 },
  // Fujitsu UK
  { month: "Aug 25", competitor: "Fujitsu UK", winRate: 66, bids: 15 },
  { month: "Sep 25", competitor: "Fujitsu UK", winRate: 68, bids: 17 },
  { month: "Oct 25", competitor: "Fujitsu UK", winRate: 71, bids: 16 },
  { month: "Nov 25", competitor: "Fujitsu UK", winRate: 69, bids: 18 },
  { month: "Dec 25", competitor: "Fujitsu UK", winRate: 72, bids: 14 },
  { month: "Jan 26", competitor: "Fujitsu UK", winRate: 70, bids: 16 },
  { month: "Feb 26", competitor: "Fujitsu UK", winRate: 73, bids: 15 },
  // CGI IT UK
  { month: "Aug 25", competitor: "CGI IT UK", winRate: 64, bids: 18 },
  { month: "Sep 25", competitor: "CGI IT UK", winRate: 66, bids: 19 },
  { month: "Oct 25", competitor: "CGI IT UK", winRate: 68, bids: 20 },
  { month: "Nov 25", competitor: "CGI IT UK", winRate: 67, bids: 17 },
  { month: "Dec 25", competitor: "CGI IT UK", winRate: 69, bids: 18 },
  { month: "Jan 26", competitor: "CGI IT UK", winRate: 68, bids: 19 },
  { month: "Feb 26", competitor: "CGI IT UK", winRate: 70, bids: 18 },
  // BAE Systems
  { month: "Aug 25", competitor: "BAE Systems", winRate: 71, bids: 8 },
  { month: "Sep 25", competitor: "BAE Systems", winRate: 73, bids: 9 },
  { month: "Oct 25", competitor: "BAE Systems", winRate: 75, bids: 7 },
  { month: "Nov 25", competitor: "BAE Systems", winRate: 74, bids: 8 },
  { month: "Dec 25", competitor: "BAE Systems", winRate: 76, bids: 6 },
  { month: "Jan 26", competitor: "BAE Systems", winRate: 72, bids: 9 },
  { month: "Feb 26", competitor: "BAE Systems", winRate: 74, bids: 8 },
];

export const MOCK_PRICING_STRATEGIES: PricingStrategy[] = [
  {
    competitor: "Capita PLC",
    category: "IT Services",
    avgDiscount: 8.5,
    typicalMargin: 18,
    priceRange: { min: 2000000, max: 6000000 },
  },
  {
    competitor: "Fujitsu UK",
    category: "Cloud Migration",
    avgDiscount: 6.2,
    typicalMargin: 22,
    priceRange: { min: 3000000, max: 8000000 },
  },
  {
    competitor: "Sopra Steria",
    category: "Digital Consulting",
    avgDiscount: 12.3,
    typicalMargin: 15,
    priceRange: { min: 1500000, max: 4500000 },
  },
  {
    competitor: "CGI IT UK",
    category: "Systems Integration",
    avgDiscount: 7.8,
    typicalMargin: 20,
    priceRange: { min: 2500000, max: 7000000 },
  },
  {
    competitor: "BAE Systems",
    category: "Cybersecurity",
    avgDiscount: 4.1,
    typicalMargin: 28,
    priceRange: { min: 4000000, max: 12000000 },
  },
  {
    competitor: "Atos UK",
    category: "Managed Services",
    avgDiscount: 10.5,
    typicalMargin: 16,
    priceRange: { min: 2000000, max: 5500000 },
  },
];

export const MOCK_TENDER_PATTERNS: TenderPattern[] = [
  { competitor: "Capita PLC", sector: "Local Government", frequency: 42, avgValue: 2800000, successRate: 64 },
  { competitor: "Capita PLC", sector: "Healthcare", frequency: 28, avgValue: 4200000, successRate: 58 },
  { competitor: "Capita PLC", sector: "Education", frequency: 35, avgValue: 1900000, successRate: 67 },
  { competitor: "Fujitsu UK", sector: "Central Government", frequency: 38, avgValue: 5500000, successRate: 71 },
  { competitor: "Fujitsu UK", sector: "Defense", frequency: 22, avgValue: 6800000, successRate: 68 },
  { competitor: "Fujitsu UK", sector: "Transport", frequency: 18, avgValue: 4100000, successRate: 72 },
  { competitor: "CGI IT UK", sector: "Healthcare", frequency: 32, avgValue: 3800000, successRate: 69 },
  { competitor: "CGI IT UK", sector: "Local Government", frequency: 44, avgValue: 2900000, successRate: 66 },
  { competitor: "CGI IT UK", sector: "Justice", frequency: 24, avgValue: 4500000, successRate: 65 },
  { competitor: "BAE Systems", sector: "Defense", frequency: 48, avgValue: 7200000, successRate: 76 },
  { competitor: "BAE Systems", sector: "Intelligence", frequency: 28, avgValue: 9100000, successRate: 78 },
  { competitor: "BAE Systems", sector: "Central Government", frequency: 16, avgValue: 5800000, successRate: 71 },
];

export const MOCK_COMPETITOR_SWOT: CompetitorSWOT[] = [
  {
    competitorId: "comp_001",
    competitorName: "Capita PLC",
    strengths: [
      "Largest market share (18.5%) in UK public sector",
      "Extensive portfolio across multiple service categories",
      "Established relationships with major government bodies",
      "Strong brand recognition and track record",
    ],
    weaknesses: [
      "Below-average win rate (62.7%) compared to premium competitors",
      "High discount rates (8.5%) indicate pricing pressure",
      "Recent negative publicity affecting reputation",
      "Lower profit margins (18%) vs competitors",
    ],
    opportunities: [
      "Digital transformation wave in local government sector",
      "Potential to leverage size for economies of scale",
      "Growing demand for integrated service solutions",
      "Expansion into emerging tech areas (AI, IoT)",
    ],
    threats: [
      "Increasing competition from specialized tech firms",
      "Government push for SME inclusion may reduce large contracts",
      "Contract rebidding cycles present retention risk",
      "Quality concerns affecting renewal rates",
    ],
    overallScore: 68,
    marketPosition: { x: 18.5, y: 62.7 },
  },
  {
    competitorId: "comp_002",
    competitorName: "Fujitsu UK",
    strengths: [
      "Highest average bid value (£4.2M) demonstrates premium positioning",
      "Strong win rate (69.8%) with consistent performance",
      "Advanced technical capabilities in cloud and infrastructure",
      "Global backing and R&D resources from parent company",
    ],
    weaknesses: [
      "Post Office Horizon scandal severely damaged UK reputation",
      "Moderate discount rates suggest pricing inflexibility",
      "Limited presence in emerging digital consulting segments",
      "Smaller bid volume (192) compared to market leaders",
    ],
    opportunities: [
      "Cloud migration boom in central government departments",
      "Cybersecurity becoming mandatory for all public contracts",
      "Potential to rebuild reputation through exemplary delivery",
      "Strategic partnerships with cloud hyperscalers",
    ],
    threats: [
      "Ongoing reputational damage from historical IT failures",
      "Aggressive competition from BAE Systems in defense sector",
      "Client diversification away from single suppliers",
      "Brexit impact on EU-based resource pools",
    ],
    overallScore: 72,
    marketPosition: { x: 15.2, y: 69.8 },
  },
  {
    competitorId: "comp_003",
    competitorName: "Sopra Steria",
    strengths: [
      "Specialized expertise in digital consulting and analytics",
      "Agile delivery methodology aligned with modern procurement",
      "Strong relationships in healthcare and education sectors",
      "Competitive pricing with strategic discount approach",
    ],
    weaknesses: [
      "Lowest win rate (57.1%) among major competitors",
      "Smallest market share (11.3%) limits influence",
      "Higher discount rates (12.3%) eroding profit margins",
      "Lower average bid values indicate mid-tier positioning",
    ],
    opportunities: [
      "NHS digital transformation creating massive opportunities",
      "Education sector modernization initiatives",
      "Data analytics becoming critical for policy decisions",
      "Potential M&A targets to expand service offerings",
    ],
    threats: [
      "Being squeezed between large integrators and niche specialists",
      "Pricing pressure from aggressive competitors",
      "Talent retention challenges in competitive market",
      "Limited brand awareness compared to household names",
    ],
    overallScore: 62,
    marketPosition: { x: 11.3, y: 57.1 },
  },
  {
    competitorId: "comp_004",
    competitorName: "CGI IT UK",
    strengths: [
      "Consistent high win rate (67.4%) with strong delivery record",
      "Balanced portfolio across systems integration and consulting",
      "Second-largest bid volume (218) shows active market presence",
      "Healthy profit margins (20%) indicate pricing power",
    ],
    weaknesses: [
      "Mid-tier market share (14.8%) lacks market dominance",
      "Moderate average bid values suggest limited mega-deal wins",
      "Generic positioning without clear differentiation",
      "Reliance on traditional SI model in evolving market",
    ],
    opportunities: [
      "Systems integration demand for legacy modernization",
      "Managed services contracts offer recurring revenue",
      "Business consulting expansion into strategic advisory",
      "Cross-selling opportunities within existing client base",
    ],
    threats: [
      "Cloud providers offering direct consulting services",
      "Automation reducing systems integration complexity",
      "Price competition from offshore delivery models",
      "Client preference for specialized over generalist firms",
    ],
    overallScore: 71,
    marketPosition: { x: 14.8, y: 67.4 },
  },
  {
    competitorId: "comp_005",
    competitorName: "BAE Systems Digital Intelligence",
    strengths: [
      "Highest win rate (73.5%) demonstrates superior competitive edge",
      "Premium pricing (£5.8M avg) with minimal discounting (4.1%)",
      "Unmatched expertise in defense and intelligence sectors",
      "Exceptional profit margins (28%) show strong value proposition",
    ],
    weaknesses: [
      "Smallest bid volume (98) due to highly selective targeting",
      "Limited presence outside defense and intelligence verticals",
      "Lowest market share (8.9%) despite high win rates",
      "Niche positioning restricts total addressable market",
    ],
    opportunities: [
      "Cybersecurity becoming mandatory across all government sectors",
      "Critical national infrastructure protection contracts",
      "Intelligence capabilities applicable to broader public sector",
      "Premium positioning in growing security-conscious market",
    ],
    threats: [
      "Specialist cybersecurity firms entering UK market",
      "Government budget constraints affecting defense spending",
      "Talent poaching by tech giants and startups",
      "Regulatory changes affecting security clearance processes",
    ],
    overallScore: 78,
    marketPosition: { x: 8.9, y: 73.5 },
  },
  {
    competitorId: "comp_006",
    competitorName: "Atos UK",
    strengths: [
      "Diverse service portfolio spanning cloud, cyber, and workplace",
      "Olympic IT heritage provides major event expertise",
      "European parent provides cross-border delivery capability",
      "Active bid pipeline (167) shows sustained market engagement",
    ],
    weaknesses: [
      "Lowest win rate (56.3%) indicates competitive challenges",
      "High discount rates (10.5%) suggest pricing desperation",
      "Lowest profit margins (16%) among tracked competitors",
      "Financial difficulties at parent level create uncertainty",
    ],
    opportunities: [
      "Digital workplace transformation accelerated by hybrid work",
      "Cloud migration projects requiring managed services",
      "Potential carve-out or acquisition could streamline operations",
      "Public sector appetite for innovative workspace solutions",
    ],
    threats: [
      "Parent company financial instability affecting UK operations",
      "Loss of key accounts to more stable competitors",
      "Talent exodus due to restructuring concerns",
      "Pricing unsustainable for long-term profitability",
    ],
    overallScore: 59,
    marketPosition: { x: 9.7, y: 56.3 },
  },
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: "insight_001",
    competitorId: "comp_001",
    category: "weakness",
    insight: "Capita's recent contract failures have created a trust deficit. Their 62.7% win rate is 11% below top performer BAE Systems, primarily due to quality concerns in delivery.",
    confidence: 92,
    impact: "high",
  },
  {
    id: "insight_002",
    competitorId: "comp_002",
    category: "threat",
    insight: "Post Office Horizon scandal continues to impact Fujitsu's reputation. Analysis shows 23% decline in healthcare sector bids where trust is paramount.",
    confidence: 88,
    impact: "high",
  },
  {
    id: "insight_003",
    competitorId: "comp_005",
    category: "strength",
    insight: "BAE Systems commands 28% profit margins vs industry average of 19%, allowing them to invest heavily in R&D while maintaining competitive pricing.",
    confidence: 95,
    impact: "high",
  },
  {
    id: "insight_004",
    competitorId: "comp_003",
    category: "opportunity",
    insight: "NHS digital transformation budget increased 40% in 2026. Sopra Steria's healthcare specialization positions them well, but win rate must improve from 57%.",
    confidence: 85,
    impact: "medium",
  },
  {
    id: "insight_005",
    competitorId: "comp_004",
    category: "strength",
    insight: "CGI's consistent 67-70% win rate over 6 months indicates strong delivery capability and client satisfaction, creating positive reference momentum.",
    confidence: 90,
    impact: "medium",
  },
  {
    id: "insight_006",
    competitorId: "comp_006",
    category: "threat",
    insight: "Atos UK's parent company restructuring has triggered a 34% increase in competitor activity targeting their existing accounts, creating churn vulnerability.",
    confidence: 87,
    impact: "high",
  },
];

export const MOCK_STRATEGIC_RECOMMENDATIONS: StrategicRecommendation[] = [
  {
    id: "rec_001",
    competitorId: "comp_001",
    competitorName: "Capita PLC",
    title: "Exploit Quality Concerns in Head-to-Head Competitions",
    description: "Capita's 62.7% win rate and recent delivery failures create an opening for quality-focused differentiation. Target contracts where they are incumbent.",
    tactics: [
      "Lead proposals with superior quality metrics and delivery guarantees",
      "Provide case studies highlighting flawless execution in similar contexts",
      "Offer fixed-price with performance penalties to demonstrate confidence",
      "Reference their recent failures (tactfully) in competitive positioning",
      "Emphasize ISO certifications and quality management frameworks",
    ],
    expectedImpact: "15-20% increase in win probability when competing head-to-head with Capita",
    priority: "high",
  },
  {
    id: "rec_002",
    competitorId: "comp_002",
    competitorName: "Fujitsu UK",
    title: "Leverage Reputational Damage in Trust-Sensitive Sectors",
    description: "Post Office Horizon scandal severely damaged Fujitsu's reputation. Healthcare and citizen-facing services show highest sensitivity to this issue.",
    tactics: [
      "Target healthcare, justice, and social services tenders where Fujitsu bids",
      "Emphasize ethical business practices and transparency commitments",
      "Highlight independent audit and oversight mechanisms",
      "Showcase citizen satisfaction scores and user feedback systems",
      "Offer enhanced transparency reporting for sensitive implementations",
    ],
    expectedImpact: "Enhanced positioning in 35% of Fujitsu's traditional sectors, particularly healthcare",
    priority: "high",
  },
  {
    id: "rec_003",
    competitorId: "comp_005",
    competitorName: "BAE Systems Digital Intelligence",
    title: "Avoid Direct Competition; Pursue Partnership Strategy",
    description: "BAE Systems' 73.5% win rate and premium positioning make head-to-head competition unfavorable. Consider partnership approach in defense/intelligence.",
    tactics: [
      "Position as specialist subcontractor for non-security components",
      "Target adjacent opportunities in critical infrastructure",
      "Develop complementary capabilities rather than competing directly",
      "Pursue joint ventures for large-scale transformation programs",
      "Focus on commercial sectors where BAE has limited presence",
    ],
    expectedImpact: "Access to £50M+ opportunities through partnership while avoiding costly competition",
    priority: "medium",
  },
  {
    id: "rec_004",
    competitorId: "comp_003",
    competitorName: "Sopra Steria",
    title: "Outbid on Price While Emphasizing Superior Delivery",
    description: "Sopra Steria's 57.1% win rate and high discount rates (12.3%) indicate pricing desperation. They can be outmaneuvered on value proposition.",
    tactics: [
      "Offer competitive pricing with superior quality guarantees",
      "Emphasize lower total cost of ownership vs. lowest initial price",
      "Highlight your win rate differential as delivery confidence indicator",
      "Target their healthcare and education renewals with better value",
      "Showcase faster implementation timelines to reduce project costs",
    ],
    expectedImpact: "Win 25-30% of opportunities where Sopra Steria is primary competitor",
    priority: "high",
  },
  {
    id: "rec_005",
    competitorId: "comp_004",
    competitorName: "CGI IT UK",
    title: "Differentiate on Innovation in Systems Integration Bids",
    description: "CGI's traditional SI approach is vulnerable to innovation-focused competitors. Their generic positioning creates differentiation opportunity.",
    tactics: [
      "Lead with AI-powered automation reducing ongoing support costs",
      "Emphasize modern cloud-native architectures vs legacy integration",
      "Offer innovation workshops and digital maturity assessments",
      "Demonstrate ROI acceleration through modern DevOps practices",
      "Position as strategic partner vs transactional service provider",
    ],
    expectedImpact: "10-15% premium pricing achievable while maintaining competitive win rates",
    priority: "medium",
  },
  {
    id: "rec_006",
    competitorId: "comp_006",
    competitorName: "Atos UK",
    title: "Aggressively Target Existing Accounts During Instability",
    description: "Atos UK's parent company financial troubles create client uncertainty. Their 56.3% win rate indicates vulnerable market position.",
    tactics: [
      "Proactively contact Atos clients offering seamless transition services",
      "Emphasize financial stability and long-term partnership capability",
      "Offer discounted migration support from Atos platforms",
      "Target their renewals with superior SLA commitments",
      "Provide 90-day price match guarantees to reduce switching risk",
    ],
    expectedImpact: "Potential to capture 15-20% of Atos's £500M UK public sector portfolio",
    priority: "high",
  },
];

export const MOCK_HEAD_TO_HEAD: HeadToHeadCompetition[] = [
  {
    id: "h2h_001",
    contractTitle: "NHS Digital Transformation Programme",
    authority: "NHS England",
    sector: "Healthcare",
    competitorId: "comp_001",
    competitorName: "Capita PLC",
    contractValue: 4200000,
    bidDate: "2025-11-15",
    outcome: "won",
    yourScore: 89,
    competitorScore: 82,
    tacticsUsed: ["Quality Guarantees", "Innovation Focus", "Competitive Pricing"],
    winningFactors: [
      "Superior technical architecture scored 12 points higher",
      "ISO 27001 certification emphasized trust and security",
      "Previous NHS delivery track record with 98% satisfaction",
      "15% lower total cost of ownership vs Capita's proposal",
    ],
  },
  {
    id: "h2h_002",
    contractTitle: "Local Government Cloud Migration",
    authority: "Manchester City Council",
    sector: "Local Government",
    competitorId: "comp_002",
    competitorName: "Fujitsu UK",
    contractValue: 3800000,
    bidDate: "2025-10-22",
    outcome: "lost",
    yourScore: 78,
    competitorScore: 85,
    tacticsUsed: ["Competitive Pricing", "Fast Delivery"],
    losingFactors: [
      "Fujitsu's existing council infrastructure gave them integration advantage",
      "Underestimated importance of legacy system knowledge",
      "Pricing was competitive but not differentiated enough",
      "Failed to highlight Fujitsu's recent reputational issues",
    ],
  },
  {
    id: "h2h_003",
    contractTitle: "Education Sector Digital Platform",
    authority: "Department for Education",
    sector: "Education",
    competitorId: "comp_003",
    competitorName: "Sopra Steria",
    contractValue: 2900000,
    bidDate: "2025-12-08",
    outcome: "won",
    yourScore: 92,
    competitorScore: 79,
    tacticsUsed: ["Quality Guarantees", "Innovation Focus", "Fast Delivery", "Case Studies"],
    winningFactors: [
      "13-point scoring advantage from innovative AI-powered learning analytics",
      "Demonstrated 40% faster implementation timeline",
      "Comprehensive case studies from similar education projects",
      "Sopra's high discount rate (12%) positioned them as desperate",
    ],
  },
  {
    id: "h2h_004",
    contractTitle: "Cybersecurity Infrastructure Upgrade",
    authority: "Home Office",
    sector: "Central Government",
    competitorId: "comp_005",
    competitorName: "BAE Systems",
    contractValue: 8500000,
    bidDate: "2025-09-30",
    outcome: "lost",
    yourScore: 81,
    competitorScore: 94,
    tacticsUsed: ["Competitive Pricing", "Quality Guarantees"],
    losingFactors: [
      "BAE's security clearance level and defense heritage unbeatable in this sector",
      "Our team lacked required SC/DV cleared personnel",
      "Pricing competition was futile against their premium positioning",
      "Should have pursued partnership/subcontractor approach instead",
    ],
  },
  {
    id: "h2h_005",
    contractTitle: "Smart City IoT Deployment",
    authority: "Birmingham City Council",
    sector: "Local Government",
    competitorId: "comp_004",
    competitorName: "CGI IT UK",
    contractValue: 3200000,
    bidDate: "2026-01-14",
    outcome: "won",
    yourScore: 87,
    competitorScore: 83,
    tacticsUsed: ["Innovation Focus", "Quality Guarantees", "Fast Delivery"],
    winningFactors: [
      "AI-powered IoT analytics positioned as next-generation vs CGI's traditional approach",
      "Cloud-native architecture vs their legacy integration model",
      "Modern DevOps delivery promised 30% faster ROI",
      "Digital maturity assessment workshop swayed procurement team",
    ],
  },
  {
    id: "h2h_006",
    contractTitle: "Transport Infrastructure Management System",
    authority: "Transport for London",
    sector: "Transport",
    competitorId: "comp_002",
    competitorName: "Fujitsu UK",
    contractValue: 6100000,
    bidDate: "2025-08-19",
    outcome: "won",
    yourScore: 91,
    competitorScore: 77,
    tacticsUsed: ["Reputation Leverage", "Quality Guarantees", "Case Studies", "Innovation Focus"],
    winningFactors: [
      "Successfully highlighted Fujitsu's Post Office Horizon scandal in trust-sensitive context",
      "Emphasized independent audit mechanisms and transparency",
      "Citizen-facing system required highest trust standards",
      "14-point scoring advantage from ethical positioning",
    ],
  },
  {
    id: "h2h_007",
    contractTitle: "Justice System Modernisation",
    authority: "Ministry of Justice",
    sector: "Justice",
    competitorId: "comp_004",
    competitorName: "CGI IT UK",
    contractValue: 5200000,
    bidDate: "2025-11-28",
    outcome: "won",
    yourScore: 88,
    competitorScore: 84,
    tacticsUsed: ["Innovation Focus", "Quality Guarantees", "Reputation Leverage"],
    winningFactors: [
      "Modern cloud-native architecture vs CGI's traditional approach",
      "AI-powered case management analytics differentiated our solution",
      "Strong security and compliance framework",
      "CGI's generic positioning made differentiation easier",
    ],
  },
  {
    id: "h2h_008",
    contractTitle: "Digital Workplace Transformation",
    authority: "Scottish Government",
    sector: "Central Government",
    competitorId: "comp_006",
    competitorName: "Atos UK",
    contractValue: 2700000,
    bidDate: "2026-02-05",
    outcome: "won",
    yourScore: 86,
    competitorScore: 74,
    tacticsUsed: ["Stability Emphasis", "Quality Guarantees", "Competitive Pricing"],
    winningFactors: [
      "Emphasized financial stability vs Atos parent company troubles",
      "Long-term partnership capability and UK commitment",
      "Offered seamless transition from their existing Atos systems",
      "12-point advantage from stability and reliability positioning",
    ],
  },
  {
    id: "h2h_009",
    contractTitle: "Healthcare Data Analytics Platform",
    authority: "Welsh Government",
    sector: "Healthcare",
    competitorId: "comp_003",
    competitorName: "Sopra Steria",
    contractValue: 3400000,
    bidDate: "2025-12-20",
    outcome: "won",
    yourScore: 90,
    competitorScore: 81,
    tacticsUsed: ["Value Proposition", "Innovation Focus", "Quality Guarantees"],
    winningFactors: [
      "Lower total cost of ownership vs Sopra's lowest initial price approach",
      "Faster implementation timeline reduced project costs by 25%",
      "Win rate differential (68% vs 57%) highlighted as delivery confidence",
      "Superior data security and GDPR compliance framework",
    ],
  },
  {
    id: "h2h_010",
    contractTitle: "Central Government ERP System",
    authority: "Cabinet Office",
    sector: "Central Government",
    competitorId: "comp_001",
    competitorName: "Capita PLC",
    contractValue: 7800000,
    bidDate: "2025-10-05",
    outcome: "lost",
    yourScore: 84,
    competitorScore: 86,
    tacticsUsed: ["Quality Guarantees", "Innovation Focus"],
    losingFactors: [
      "Capita's existing Cabinet Office relationships proved decisive",
      "Underestimated value of incumbent advantage",
      "Only 2-point scoring gap - very close competition",
      "Should have emphasized their recent delivery failures more strongly",
    ],
  },
];

export const MOCK_TACTIC_EFFECTIVENESS: TacticEffectiveness[] = [
  {
    tactic: "Innovation Focus",
    timesUsed: 7,
    wins: 6,
    losses: 1,
    winRate: 85.7,
    avgScoreImprovement: 8.2,
    bestAgainst: ["CGI IT UK", "Sopra Steria"],
    worstAgainst: ["BAE Systems"],
  },
  {
    tactic: "Quality Guarantees",
    timesUsed: 8,
    wins: 6,
    losses: 2,
    winRate: 75.0,
    avgScoreImprovement: 6.5,
    bestAgainst: ["Capita PLC", "Sopra Steria"],
    worstAgainst: ["BAE Systems"],
  },
  {
    tactic: "Competitive Pricing",
    timesUsed: 4,
    wins: 1,
    losses: 3,
    winRate: 25.0,
    avgScoreImprovement: -2.1,
    bestAgainst: ["Sopra Steria"],
    worstAgainst: ["Fujitsu UK", "BAE Systems"],
  },
  {
    tactic: "Reputation Leverage",
    timesUsed: 3,
    wins: 3,
    losses: 0,
    winRate: 100.0,
    avgScoreImprovement: 12.3,
    bestAgainst: ["Fujitsu UK"],
    worstAgainst: [],
  },
  {
    tactic: "Fast Delivery",
    timesUsed: 4,
    wins: 3,
    losses: 1,
    winRate: 75.0,
    avgScoreImprovement: 5.8,
    bestAgainst: ["Sopra Steria", "CGI IT UK"],
    worstAgainst: ["Fujitsu UK"],
  },
  {
    tactic: "Case Studies",
    timesUsed: 3,
    wins: 2,
    losses: 1,
    winRate: 66.7,
    avgScoreImprovement: 4.3,
    bestAgainst: ["Sopra Steria"],
    worstAgainst: ["Fujitsu UK"],
  },
  {
    tactic: "Stability Emphasis",
    timesUsed: 1,
    wins: 1,
    losses: 0,
    winRate: 100.0,
    avgScoreImprovement: 12.0,
    bestAgainst: ["Atos UK"],
    worstAgainst: [],
  },
  {
    tactic: "Value Proposition",
    timesUsed: 1,
    wins: 1,
    losses: 0,
    winRate: 100.0,
    avgScoreImprovement: 9.0,
    bestAgainst: ["Sopra Steria"],
    worstAgainst: [],
  },
];

export const MOCK_COMPETITOR_H2H: CompetitorHeadToHead[] = [
  {
    competitorId: "comp_001",
    competitorName: "Capita PLC",
    totalCompetitions: 2,
    wins: 1,
    losses: 1,
    winRate: 50.0,
    avgMargin: 3.5,
    totalValue: 12000000,
    recentTrend: "stable",
  },
  {
    competitorId: "comp_002",
    competitorName: "Fujitsu UK",
    totalCompetitions: 2,
    wins: 1,
    losses: 1,
    winRate: 50.0,
    avgMargin: 7.0,
    totalValue: 9900000,
    recentTrend: "improving",
  },
  {
    competitorId: "comp_003",
    competitorName: "Sopra Steria",
    totalCompetitions: 2,
    wins: 2,
    losses: 0,
    winRate: 100.0,
    avgMargin: 10.5,
    totalValue: 6300000,
    recentTrend: "stable",
  },
  {
    competitorId: "comp_004",
    competitorName: "CGI IT UK",
    totalCompetitions: 2,
    wins: 2,
    losses: 0,
    winRate: 100.0,
    avgMargin: 4.5,
    totalValue: 8400000,
    recentTrend: "stable",
  },
  {
    competitorId: "comp_005",
    competitorName: "BAE Systems",
    totalCompetitions: 1,
    wins: 0,
    losses: 1,
    winRate: 0.0,
    avgMargin: -13.0,
    totalValue: 8500000,
    recentTrend: "declining",
  },
  {
    competitorId: "comp_006",
    competitorName: "Atos UK",
    totalCompetitions: 1,
    wins: 1,
    losses: 0,
    winRate: 100.0,
    avgMargin: 12.0,
    totalValue: 2700000,
    recentTrend: "stable",
  },
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "tm_001",
    name: "Sarah Mitchell",
    role: "Project Manager",
    expertise: ["Healthcare", "Digital Transformation", "Agile Delivery"],
    totalBids: 8,
    wins: 7,
    losses: 1,
    winRate: 87.5,
    avgScoreContribution: 8.4,
    yearsExperience: 12,
  },
  {
    id: "tm_002",
    name: "James Chen",
    role: "Technical Lead",
    expertise: ["Cloud Architecture", "Cybersecurity", "AI/ML"],
    totalBids: 7,
    wins: 6,
    losses: 1,
    winRate: 85.7,
    avgScoreContribution: 9.1,
    yearsExperience: 15,
  },
  {
    id: "tm_003",
    name: "Emma Thompson",
    role: "Bid Writer",
    expertise: ["Technical Writing", "Compliance", "Value Proposition"],
    totalBids: 9,
    wins: 6,
    losses: 3,
    winRate: 66.7,
    avgScoreContribution: 7.2,
    yearsExperience: 8,
  },
  {
    id: "tm_004",
    name: "Michael Roberts",
    role: "Project Manager",
    expertise: ["Local Government", "Smart Cities", "IoT"],
    totalBids: 6,
    wins: 3,
    losses: 3,
    winRate: 50.0,
    avgScoreContribution: 5.8,
    yearsExperience: 9,
  },
  {
    id: "tm_005",
    name: "Priya Patel",
    role: "Technical Lead",
    expertise: ["Data Analytics", "Machine Learning", "Integration"],
    totalBids: 5,
    wins: 3,
    losses: 2,
    winRate: 60.0,
    avgScoreContribution: 6.7,
    yearsExperience: 10,
  },
  {
    id: "tm_006",
    name: "David Armstrong",
    role: "Bid Writer",
    expertise: ["Strategic Messaging", "Win Themes", "Executive Summaries"],
    totalBids: 4,
    wins: 4,
    losses: 0,
    winRate: 100.0,
    avgScoreContribution: 8.8,
    yearsExperience: 14,
  },
  {
    id: "tm_007",
    name: "Lisa Wong",
    role: "Subject Matter Expert",
    expertise: ["Healthcare IT", "Clinical Systems", "NHS Frameworks"],
    totalBids: 3,
    wins: 3,
    losses: 0,
    winRate: 100.0,
    avgScoreContribution: 9.5,
    yearsExperience: 18,
  },
  {
    id: "tm_008",
    name: "Robert Taylor",
    role: "Pricing Specialist",
    expertise: ["Cost Modeling", "Value Engineering", "Commercial Strategy"],
    totalBids: 6,
    wins: 5,
    losses: 1,
    winRate: 83.3,
    avgScoreContribution: 7.6,
    yearsExperience: 11,
  },
];

export const MOCK_TEAM_COMPOSITIONS: TeamComposition[] = [
  {
    competitionId: "h2h_001",
    projectManager: "Sarah Mitchell",
    technicalLead: "James Chen",
    bidWriter: "Emma Thompson",
    pricingSpecialist: "Robert Taylor",
    subjectMatterExperts: ["Lisa Wong"],
    teamSize: 5,
  },
  {
    competitionId: "h2h_002",
    projectManager: "Michael Roberts",
    technicalLead: "Priya Patel",
    bidWriter: "Emma Thompson",
    subjectMatterExperts: [],
    teamSize: 3,
  },
  {
    competitionId: "h2h_003",
    projectManager: "Sarah Mitchell",
    technicalLead: "James Chen",
    bidWriter: "David Armstrong",
    pricingSpecialist: "Robert Taylor",
    subjectMatterExperts: [],
    teamSize: 4,
  },
  {
    competitionId: "h2h_004",
    projectManager: "Michael Roberts",
    technicalLead: "James Chen",
    bidWriter: "Emma Thompson",
    subjectMatterExperts: [],
    teamSize: 3,
  },
  {
    competitionId: "h2h_005",
    projectManager: "Sarah Mitchell",
    technicalLead: "Priya Patel",
    bidWriter: "David Armstrong",
    pricingSpecialist: "Robert Taylor",
    subjectMatterExperts: [],
    teamSize: 4,
  },
  {
    competitionId: "h2h_006",
    projectManager: "Sarah Mitchell",
    technicalLead: "James Chen",
    bidWriter: "David Armstrong",
    pricingSpecialist: "Robert Taylor",
    subjectMatterExperts: ["Lisa Wong"],
    teamSize: 5,
  },
  {
    competitionId: "h2h_007",
    projectManager: "Sarah Mitchell",
    technicalLead: "James Chen",
    bidWriter: "Emma Thompson",
    subjectMatterExperts: [],
    teamSize: 3,
  },
  {
    competitionId: "h2h_008",
    projectManager: "Sarah Mitchell",
    technicalLead: "Priya Patel",
    bidWriter: "David Armstrong",
    pricingSpecialist: "Robert Taylor",
    subjectMatterExperts: [],
    teamSize: 4,
  },
  {
    competitionId: "h2h_009",
    projectManager: "Sarah Mitchell",
    technicalLead: "James Chen",
    bidWriter: "Emma Thompson",
    pricingSpecialist: "Robert Taylor",
    subjectMatterExperts: ["Lisa Wong"],
    teamSize: 5,
  },
  {
    competitionId: "h2h_010",
    projectManager: "Michael Roberts",
    technicalLead: "James Chen",
    bidWriter: "Emma Thompson",
    subjectMatterExperts: [],
    teamSize: 3,
  },
];

export const MOCK_TEAM_PERFORMANCE_BY_COMPETITOR: TeamPerformanceMetric[] = [
  // Sarah Mitchell vs Competitors
  { teamMemberId: "tm_001", memberName: "Sarah Mitchell", role: "PM", competitorId: "comp_001", competitorName: "Capita PLC", appearances: 1, wins: 0, losses: 1, winRate: 0, avgScoreContribution: 7.2 },
  { teamMemberId: "tm_001", memberName: "Sarah Mitchell", role: "PM", competitorId: "comp_002", competitorName: "Fujitsu UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 9.1 },
  { teamMemberId: "tm_001", memberName: "Sarah Mitchell", role: "PM", competitorId: "comp_003", competitorName: "Sopra Steria", appearances: 2, wins: 2, losses: 0, winRate: 100, avgScoreContribution: 9.0 },
  { teamMemberId: "tm_001", memberName: "Sarah Mitchell", role: "PM", competitorId: "comp_004", competitorName: "CGI IT UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 8.7 },
  { teamMemberId: "tm_001", memberName: "Sarah Mitchell", role: "PM", competitorId: "comp_006", competitorName: "Atos UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 8.6 },
  // James Chen vs Competitors
  { teamMemberId: "tm_002", memberName: "James Chen", role: "TL", competitorId: "comp_001", competitorName: "Capita PLC", appearances: 2, wins: 1, losses: 1, winRate: 50, avgScoreContribution: 8.0 },
  { teamMemberId: "tm_002", memberName: "James Chen", role: "TL", competitorId: "comp_002", competitorName: "Fujitsu UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 9.8 },
  { teamMemberId: "tm_002", memberName: "James Chen", role: "TL", competitorId: "comp_003", competitorName: "Sopra Steria", appearances: 2, wins: 2, losses: 0, winRate: 100, avgScoreContribution: 9.5 },
  { teamMemberId: "tm_002", memberName: "James Chen", role: "TL", competitorId: "comp_004", competitorName: "CGI IT UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 9.2 },
  { teamMemberId: "tm_002", memberName: "James Chen", role: "TL", competitorId: "comp_005", competitorName: "BAE Systems", appearances: 1, wins: 0, losses: 1, winRate: 0, avgScoreContribution: 6.8 },
  // David Armstrong vs Competitors
  { teamMemberId: "tm_006", memberName: "David Armstrong", role: "BW", competitorId: "comp_002", competitorName: "Fujitsu UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 9.1 },
  { teamMemberId: "tm_006", memberName: "David Armstrong", role: "BW", competitorId: "comp_003", competitorName: "Sopra Steria", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 8.9 },
  { teamMemberId: "tm_006", memberName: "David Armstrong", role: "BW", competitorId: "comp_004", competitorName: "CGI IT UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 8.5 },
  { teamMemberId: "tm_006", memberName: "David Armstrong", role: "BW", competitorId: "comp_006", competitorName: "Atos UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 8.7 },
  // Emma Thompson vs Competitors
  { teamMemberId: "tm_003", memberName: "Emma Thompson", role: "BW", competitorId: "comp_001", competitorName: "Capita PLC", appearances: 2, wins: 1, losses: 1, winRate: 50, avgScoreContribution: 7.4 },
  { teamMemberId: "tm_003", memberName: "Emma Thompson", role: "BW", competitorId: "comp_002", competitorName: "Fujitsu UK", appearances: 1, wins: 0, losses: 1, winRate: 0, avgScoreContribution: 6.5 },
  { teamMemberId: "tm_003", memberName: "Emma Thompson", role: "BW", competitorId: "comp_003", competitorName: "Sopra Steria", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 7.8 },
  { teamMemberId: "tm_003", memberName: "Emma Thompson", role: "BW", competitorId: "comp_004", competitorName: "CGI IT UK", appearances: 1, wins: 1, losses: 0, winRate: 100, avgScoreContribution: 7.2 },
  { teamMemberId: "tm_003", memberName: "Emma Thompson", role: "BW", competitorId: "comp_005", competitorName: "BAE Systems", appearances: 1, wins: 0, losses: 1, winRate: 0, avgScoreContribution: 6.8 },
];

export const MOCK_OPTIMAL_TEAM_RECOMMENDATIONS: OptimalTeamRecommendation[] = [
  {
    competitorId: "comp_001",
    competitorName: "Capita PLC",
    recommendedPM: "Sarah Mitchell",
    recommendedTL: "James Chen",
    recommendedBW: "David Armstrong",
    recommendedSMEs: ["Lisa Wong"],
    reasoning: [
      "Sarah Mitchell has 100% win rate vs Capita in quality-focused positioning",
      "James Chen's technical depth counters Capita's delivery concerns",
      "David Armstrong's strategic messaging amplifies differentiation",
      "Lisa Wong's NHS expertise provides credibility in healthcare bids",
    ],
    expectedWinRate: 85,
    confidence: 88,
  },
  {
    competitorId: "comp_002",
    competitorName: "Fujitsu UK",
    recommendedPM: "Sarah Mitchell",
    recommendedTL: "James Chen",
    recommendedBW: "David Armstrong",
    recommendedSMEs: ["Lisa Wong"],
    reasoning: [
      "This exact team won Transport for London (91 vs 77) using reputation leverage",
      "Sarah Mitchell excels at trust-sensitive positioning (100% vs Fujitsu)",
      "David Armstrong's messaging expertise critical for ethical differentiation",
      "James Chen's security credentials counter Fujitsu's technical strengths",
    ],
    expectedWinRate: 92,
    confidence: 95,
  },
  {
    competitorId: "comp_003",
    competitorName: "Sopra Steria",
    recommendedPM: "Sarah Mitchell",
    recommendedTL: "James Chen",
    recommendedBW: "David Armstrong",
    recommendedSMEs: ["Lisa Wong"],
    reasoning: [
      "Perfect record (2-0) with Sarah/James/David combination vs Sopra Steria",
      "Team's value proposition messaging consistently beats Sopra's price focus",
      "James Chen's innovation expertise exploits Sopra's traditional approach",
      "David Armstrong's 100% win rate includes both Sopra competitions",
    ],
    expectedWinRate: 95,
    confidence: 94,
  },
  {
    competitorId: "comp_004",
    competitorName: "CGI IT UK",
    recommendedPM: "Sarah Mitchell",
    recommendedTL: "Priya Patel",
    recommendedBW: "David Armstrong",
    recommendedSMEs: [],
    reasoning: [
      "Innovation differentiation strategy works perfectly against CGI's traditional SI",
      "Priya Patel's data analytics expertise creates differentiation in IoT/Smart City bids",
      "Sarah Mitchell's agile delivery positioning counters CGI's slower methodology",
      "David Armstrong's strategic partner messaging vs CGI's transactional approach",
    ],
    expectedWinRate: 88,
    confidence: 86,
  },
  {
    competitorId: "comp_005",
    competitorName: "BAE Systems",
    recommendedPM: "Sarah Mitchell",
    recommendedTL: "James Chen",
    recommendedBW: "David Armstrong",
    recommendedSMEs: [],
    reasoning: [
      "Recommendation: Avoid direct competition or pursue partnership approach",
      "If competition unavoidable, use highest-performing team to minimize loss",
      "James Chen's security clearance maximizes competitiveness",
      "Focus on adjacent opportunities outside defense/intelligence core",
    ],
    expectedWinRate: 35,
    confidence: 78,
  },
  {
    competitorId: "comp_006",
    competitorName: "Atos UK",
    recommendedPM: "Sarah Mitchell",
    recommendedTL: "Priya Patel",
    recommendedBW: "David Armstrong",
    recommendedSMEs: [],
    reasoning: [
      "Won Scottish Government with Sarah/Priya/David using stability messaging",
      "Sarah Mitchell's long-term partnership positioning critical vs troubled Atos",
      "David Armstrong's messaging exploits Atos parent company uncertainty",
      "Priya Patel's modern architecture approach highlights Atos technical debt",
    ],
    expectedWinRate: 90,
    confidence: 91,
  },
];

export const MOCK_TEAM_PERFORMANCE_TRENDS: TeamPerformanceTrend[] = [
  // Sarah Mitchell trend
  { month: "Sep 25", teamMemberId: "tm_001", memberName: "Sarah Mitchell", winRate: 100, bidsLed: 1 },
  { month: "Oct 25", teamMemberId: "tm_001", memberName: "Sarah Mitchell", winRate: 0, bidsLed: 1 },
  { month: "Nov 25", teamMemberId: "tm_001", memberName: "Sarah Mitchell", winRate: 100, bidsLed: 1 },
  { month: "Dec 25", teamMemberId: "tm_001", memberName: "Sarah Mitchell", winRate: 100, bidsLed: 2 },
  { month: "Jan 26", teamMemberId: "tm_001", memberName: "Sarah Mitchell", winRate: 100, bidsLed: 1 },
  { month: "Feb 26", teamMemberId: "tm_001", memberName: "Sarah Mitchell", winRate: 100, bidsLed: 1 },
  // James Chen trend
  { month: "Aug 25", teamMemberId: "tm_002", memberName: "James Chen", winRate: 100, bidsLed: 1 },
  { month: "Sep 25", teamMemberId: "tm_002", memberName: "James Chen", winRate: 0, bidsLed: 1 },
  { month: "Oct 25", teamMemberId: "tm_002", memberName: "James Chen", winRate: 0, bidsLed: 1 },
  { month: "Nov 25", teamMemberId: "tm_002", memberName: "James Chen", winRate: 100, bidsLed: 1 },
  { month: "Dec 25", teamMemberId: "tm_002", memberName: "James Chen", winRate: 100, bidsLed: 2 },
  { month: "Jan 26", teamMemberId: "tm_002", memberName: "James Chen", winRate: 100, bidsLed: 1 },
  // David Armstrong trend
  { month: "Aug 25", teamMemberId: "tm_006", memberName: "David Armstrong", winRate: 100, bidsLed: 1 },
  { month: "Nov 25", teamMemberId: "tm_006", memberName: "David Armstrong", winRate: 100, bidsLed: 1 },
  { month: "Dec 25", teamMemberId: "tm_006", memberName: "David Armstrong", winRate: 100, bidsLed: 1 },
  { month: "Feb 26", teamMemberId: "tm_006", memberName: "David Armstrong", winRate: 100, bidsLed: 1 },
];

export const MOCK_TEAM_COLLABORATIONS: TeamCollaboration[] = [
  // Sarah Mitchell collaborations
  { memberId1: "tm_001", memberName1: "Sarah Mitchell", role1: "PM", memberId2: "tm_002", memberName2: "James Chen", role2: "TL", collaborations: 6, wins: 5, losses: 1, winRate: 83.3, avgCombinedScore: 89.2, chemistry: "excellent" },
  { memberId1: "tm_001", memberName1: "Sarah Mitchell", role1: "PM", memberId2: "tm_003", memberName2: "Emma Thompson", role2: "BW", collaborations: 4, wins: 3, losses: 1, winRate: 75.0, avgCombinedScore: 85.3, chemistry: "good" },
  { memberId1: "tm_001", memberName1: "Sarah Mitchell", role1: "PM", memberId2: "tm_005", memberName2: "Priya Patel", role2: "TL", collaborations: 2, wins: 2, losses: 0, winRate: 100.0, avgCombinedScore: 87.5, chemistry: "excellent" },
  { memberId1: "tm_001", memberName1: "Sarah Mitchell", role1: "PM", memberId2: "tm_006", memberName2: "David Armstrong", role2: "BW", collaborations: 3, wins: 3, losses: 0, winRate: 100.0, avgCombinedScore: 91.3, chemistry: "excellent" },
  { memberId1: "tm_001", memberName1: "Sarah Mitchell", role1: "PM", memberId2: "tm_007", memberName2: "Lisa Wong", role2: "SME", collaborations: 3, wins: 3, losses: 0, winRate: 100.0, avgCombinedScore: 90.0, chemistry: "excellent" },
  { memberId1: "tm_001", memberName1: "Sarah Mitchell", role1: "PM", memberId2: "tm_008", memberName2: "Robert Taylor", role2: "Pricing", collaborations: 5, wins: 4, losses: 1, winRate: 80.0, avgCombinedScore: 87.0, chemistry: "good" },
  // James Chen collaborations
  { memberId1: "tm_002", memberName1: "James Chen", role1: "TL", memberId2: "tm_003", memberName2: "Emma Thompson", role2: "BW", collaborations: 4, wins: 3, losses: 1, winRate: 75.0, avgCombinedScore: 84.8, chemistry: "good" },
  { memberId1: "tm_002", memberName1: "James Chen", role1: "TL", memberId2: "tm_006", memberName2: "David Armstrong", role2: "BW", collaborations: 3, wins: 3, losses: 0, winRate: 100.0, avgCombinedScore: 90.7, chemistry: "excellent" },
  { memberId1: "tm_002", memberName1: "James Chen", role1: "TL", memberId2: "tm_007", memberName2: "Lisa Wong", role2: "SME", collaborations: 3, wins: 3, losses: 0, winRate: 100.0, avgCombinedScore: 91.5, chemistry: "excellent" },
  { memberId1: "tm_002", memberName1: "James Chen", role1: "TL", memberId2: "tm_008", memberName2: "Robert Taylor", role2: "Pricing", collaborations: 4, wins: 3, losses: 1, winRate: 75.0, avgCombinedScore: 86.5, chemistry: "good" },
  // Michael Roberts collaborations
  { memberId1: "tm_004", memberName1: "Michael Roberts", role1: "PM", memberId2: "tm_002", memberName2: "James Chen", role2: "TL", collaborations: 2, wins: 0, losses: 2, winRate: 0.0, avgCombinedScore: 79.5, chemistry: "poor" },
  { memberId1: "tm_004", memberName1: "Michael Roberts", role1: "PM", memberId2: "tm_003", memberName2: "Emma Thompson", role2: "BW", collaborations: 2, wins: 0, losses: 2, winRate: 0.0, avgCombinedScore: 78.0, chemistry: "poor" },
  { memberId1: "tm_004", memberName1: "Michael Roberts", role1: "PM", memberId2: "tm_005", memberName2: "Priya Patel", role2: "TL", collaborations: 1, wins: 0, losses: 1, winRate: 0.0, avgCombinedScore: 78.0, chemistry: "poor" },
  // Priya Patel collaborations
  { memberId1: "tm_005", memberName1: "Priya Patel", role1: "TL", memberId2: "tm_006", memberName2: "David Armstrong", role2: "BW", collaborations: 2, wins: 2, losses: 0, winRate: 100.0, avgCombinedScore: 87.0, chemistry: "excellent" },
  { memberId1: "tm_005", memberName1: "Priya Patel", role1: "TL", memberId2: "tm_008", memberName2: "Robert Taylor", role2: "Pricing", collaborations: 2, wins: 2, losses: 0, winRate: 100.0, avgCombinedScore: 86.5, chemistry: "good" },
  // David Armstrong collaborations
  { memberId1: "tm_006", memberName1: "David Armstrong", role1: "BW", memberId2: "tm_007", memberName2: "Lisa Wong", role2: "SME", collaborations: 1, wins: 1, losses: 0, winRate: 100.0, avgCombinedScore: 91.0, chemistry: "excellent" },
  { memberId1: "tm_006", memberName1: "David Armstrong", role1: "BW", memberId2: "tm_008", memberName2: "Robert Taylor", role2: "Pricing", collaborations: 4, wins: 4, losses: 0, winRate: 100.0, avgCombinedScore: 88.8, chemistry: "excellent" },
  // Emma Thompson collaborations
  { memberId1: "tm_003", memberName1: "Emma Thompson", role1: "BW", memberId2: "tm_007", memberName2: "Lisa Wong", role2: "SME", collaborations: 2, wins: 2, losses: 0, winRate: 100.0, avgCombinedScore: 89.5, chemistry: "good" },
  { memberId1: "tm_003", memberName1: "Emma Thompson", role1: "BW", memberId2: "tm_008", memberName2: "Robert Taylor", role2: "Pricing", collaborations: 4, wins: 3, losses: 1, winRate: 75.0, avgCombinedScore: 84.3, chemistry: "good" },
];

export const MOCK_COLLABORATION_PATTERNS: CollaborationPattern[] = [
  {
    id: "cp_001",
    pattern: "Sarah Mitchell (PM) + James Chen (TL)",
    description: "This PM-TL pairing creates exceptional technical delivery with strong stakeholder management",
    frequency: 6,
    winRate: 83.3,
    avgMargin: 7.8,
    examples: ["NHS Digital Transformation (89 vs 82)", "Transport for London (91 vs 77)", "Justice System (88 vs 84)"],
    impact: "high",
  },
  {
    id: "cp_002",
    pattern: "Sarah Mitchell (PM) + David Armstrong (BW)",
    description: "Perfect 100% win rate combination with superior messaging and delivery positioning",
    frequency: 3,
    winRate: 100.0,
    avgMargin: 10.3,
    examples: ["Education Platform (92 vs 79)", "Transport for London (91 vs 77)", "Smart City IoT (87 vs 83)"],
    impact: "high",
  },
  {
    id: "cp_003",
    pattern: "James Chen (TL) + David Armstrong (BW)",
    description: "Technical excellence combined with strategic messaging creates unbeatable proposals",
    frequency: 3,
    winRate: 100.0,
    avgMargin: 9.7,
    examples: ["Education Platform (92 vs 79)", "Transport for London (91 vs 77)", "Smart City IoT (87 vs 83)"],
    impact: "high",
  },
  {
    id: "cp_004",
    pattern: "James Chen (TL) + Lisa Wong (SME)",
    description: "Technical depth with healthcare specialization dominates complex NHS and healthcare bids",
    frequency: 3,
    winRate: 100.0,
    avgMargin: 11.0,
    examples: ["NHS Digital Transformation (89 vs 82)", "Transport for London (91 vs 77)", "Healthcare Analytics (90 vs 81)"],
    impact: "high",
  },
  {
    id: "cp_005",
    pattern: "David Armstrong (BW) + Robert Taylor (Pricing)",
    description: "Strategic messaging combined with commercial excellence delivers value-focused wins",
    frequency: 4,
    winRate: 100.0,
    avgMargin: 9.5,
    examples: ["Education Platform (92 vs 79)", "Transport for London (91 vs 77)", "Healthcare Analytics (90 vs 81)"],
    impact: "high",
  },
  {
    id: "cp_006",
    pattern: "Sarah Mitchell (PM) + Priya Patel (TL)",
    description: "Perfect 100% win rate in innovation-focused bids leveraging data analytics expertise",
    frequency: 2,
    winRate: 100.0,
    avgMargin: 6.5,
    examples: ["Smart City IoT (87 vs 83)", "Digital Workplace (86 vs 74)"],
    impact: "medium",
  },
  {
    id: "cp_007",
    pattern: "Michael Roberts (PM) + Any Team Member",
    description: "WARNING: All Michael Roberts pairings show 0% win rate - consider coaching or role change",
    frequency: 5,
    winRate: 0.0,
    avgMargin: -5.8,
    examples: ["Cloud Migration (78 vs 85 - LOST)", "Cybersecurity Infrastructure (81 vs 94 - LOST)", "ERP System (84 vs 86 - LOST)"],
    impact: "high",
  },
];

export const MOCK_NETWORK_METRICS: TeamMemberNetworkMetrics[] = [
  { memberId: "tm_001", memberName: "Sarah Mitchell", role: "PM", totalConnections: 6, strongConnections: 4, weakConnections: 2, isolationScore: 5, centralityScore: 95, collaborationQuality: 88.5 },
  { memberId: "tm_002", memberName: "James Chen", role: "TL", totalConnections: 5, strongConnections: 4, weakConnections: 1, isolationScore: 8, centralityScore: 92, collaborationQuality: 87.7 },
  { memberId: "tm_003", memberName: "Emma Thompson", role: "BW", totalConnections: 4, strongConnections: 2, weakConnections: 2, isolationScore: 15, centralityScore: 68, collaborationQuality: 85.7 },
  { memberId: "tm_004", memberName: "Michael Roberts", role: "PM", totalConnections: 3, strongConnections: 0, weakConnections: 3, isolationScore: 78, centralityScore: 22, collaborationQuality: 78.5 },
  { memberId: "tm_005", memberName: "Priya Patel", role: "TL", totalConnections: 3, strongConnections: 3, weakConnections: 0, isolationScore: 12, centralityScore: 75, collaborationQuality: 87.0 },
  { memberId: "tm_006", memberName: "David Armstrong", role: "BW", totalConnections: 4, strongConnections: 4, weakConnections: 0, isolationScore: 10, centralityScore: 88, collaborationQuality: 90.2 },
  { memberId: "tm_007", memberName: "Lisa Wong", role: "SME", totalConnections: 3, strongConnections: 3, weakConnections: 0, isolationScore: 18, centralityScore: 65, collaborationQuality: 90.3 },
  { memberId: "tm_008", memberName: "Robert Taylor", role: "Pricing", totalConnections: 4, strongConnections: 2, weakConnections: 2, isolationScore: 14, centralityScore: 72, collaborationQuality: 86.6 },
];

export const MOCK_OPTIMAL_CHEMISTRY: OptimalChemistry[] = [
  {
    competitorId: "comp_001",
    competitorName: "Capita PLC",
    recommendedPairs: [
      { member1: "Sarah Mitchell", member2: "James Chen", role1: "PM", role2: "TL", synergy: "Quality-focused delivery positioning" },
      { member1: "Sarah Mitchell", member2: "David Armstrong", role1: "PM", role2: "BW", synergy: "Superior messaging amplifies differentiation" },
      { member1: "James Chen", member2: "Robert Taylor", role1: "TL", role2: "Pricing", synergy: "Technical depth with competitive commercial strategy" },
    ],
    reasoning: [
      "Sarah-James pairing achieved 83.3% win rate with 7.8-point average margin",
      "Sarah-David combination has perfect 100% win rate (3/3)",
      "Capita's quality concerns best countered by strong PM-TL chemistry",
    ],
    expectedSynergy: 88,
    confidence: 92,
  },
  {
    competitorId: "comp_002",
    competitorName: "Fujitsu UK",
    recommendedPairs: [
      { member1: "Sarah Mitchell", member2: "David Armstrong", role1: "PM", role2: "BW", synergy: "Trust and ethics messaging expertise" },
      { member1: "James Chen", member2: "Lisa Wong", role1: "TL", role2: "SME", synergy: "Technical credibility in healthcare sector" },
      { member1: "David Armstrong", member2: "Robert Taylor", role1: "BW", role2: "Pricing", synergy: "Value-focused positioning vs reputation issues" },
    ],
    reasoning: [
      "Sarah-David perfect chemistry (100% win rate) ideal for reputation leverage tactics",
      "James-Lisa combination unbeatable in healthcare (100% win rate, 11-point margin)",
      "David-Robert pairing delivers strategic messaging with commercial strength",
    ],
    expectedSynergy: 94,
    confidence: 96,
  },
  {
    competitorId: "comp_003",
    competitorName: "Sopra Steria",
    recommendedPairs: [
      { member1: "Sarah Mitchell", member2: "James Chen", role1: "PM", role2: "TL", synergy: "Value proposition over price differentiation" },
      { member1: "James Chen", member2: "David Armstrong", role1: "TL", role2: "BW", synergy: "Innovation messaging excellence" },
      { member1: "Sarah Mitchell", member2: "David Armstrong", role1: "PM", role2: "BW", synergy: "Delivery confidence positioning" },
    ],
    reasoning: [
      "All recommended pairs have 100% win rate against Sopra Steria",
      "James-David combo achieves 9.7-point average margin with innovation focus",
      "Sarah-James-David trio won both Sopra competitions (92 vs 79, 90 vs 81)",
    ],
    expectedSynergy: 96,
    confidence: 98,
  },
  {
    competitorId: "comp_004",
    competitorName: "CGI IT UK",
    recommendedPairs: [
      { member1: "Sarah Mitchell", member2: "Priya Patel", role1: "PM", role2: "TL", synergy: "Innovation and agility vs traditional SI" },
      { member1: "Priya Patel", member2: "David Armstrong", role1: "TL", role2: "BW", synergy: "Data analytics expertise with strategic messaging" },
      { member1: "Sarah Mitchell", member2: "David Armstrong", role1: "PM", role2: "BW", synergy: "Modern delivery positioning" },
    ],
    reasoning: [
      "Sarah-Priya perfect chemistry (100% win rate) in IoT and modern tech bids",
      "Priya-David combination ideal for data-driven differentiation",
      "Sarah-David pairing won both CGI competitions (87 vs 83, 88 vs 84)",
    ],
    expectedSynergy: 90,
    confidence: 89,
  },
  {
    competitorId: "comp_005",
    competitorName: "BAE Systems",
    recommendedPairs: [
      { member1: "Sarah Mitchell", member2: "James Chen", role1: "PM", role2: "TL", synergy: "Maximum technical credibility" },
      { member1: "James Chen", member2: "David Armstrong", role1: "TL", role2: "BW", synergy: "Security expertise with quality messaging" },
    ],
    reasoning: [
      "Recommendation: Avoid direct competition - these pairs minimize loss if unavoidable",
      "Sarah-James highest overall chemistry (83.3% win rate, 89.2 avg score)",
      "James Chen's security credentials essential against BAE",
    ],
    expectedSynergy: 45,
    confidence: 65,
  },
  {
    competitorId: "comp_006",
    competitorName: "Atos UK",
    recommendedPairs: [
      { member1: "Sarah Mitchell", member2: "Priya Patel", role1: "PM", role2: "TL", synergy: "Stability and modern architecture messaging" },
      { member1: "Priya Patel", member2: "David Armstrong", role1: "TL", role2: "BW", synergy: "Innovation vs legacy systems" },
      { member1: "David Armstrong", member2: "Robert Taylor", role1: "BW", role2: "Pricing", synergy: "Strategic positioning with commercial strength" },
    ],
    reasoning: [
      "Sarah-Priya-David won Scottish Government (86 vs 74) using stability messaging",
      "Priya-David chemistry perfect for highlighting Atos technical debt",
      "All recommended pairs show excellent to good chemistry ratings",
    ],
    expectedSynergy: 92,
    confidence: 93,
  },
];

export const MOCK_COLLABORATION_TIMELINE: CollaborationTimelineEvent[] = [
  {
    id: "timeline_001",
    date: "2024-06-15",
    eventType: "new_hire",
    title: "David Armstrong Joins Team",
    description: "Experienced bid writer with 14 years of strategic messaging expertise joins the team, bringing exceptional win theme development skills",
    participants: ["David Armstrong"],
    impact: "positive",
    chemistryScore: 90,
  },
  {
    id: "timeline_002",
    date: "2024-07-01",
    eventType: "team_formation",
    title: "First Sarah-James Collaboration",
    description: "Sarah Mitchell (PM) and James Chen (TL) paired for the first time on a healthcare project, establishing what would become a winning partnership",
    participants: ["Sarah Mitchell", "James Chen"],
    impact: "positive",
    chemistryScore: 82,
  },
  {
    id: "timeline_003",
    date: "2024-08-19",
    eventType: "project_win",
    title: "Transport for London Win - Breakthrough Moment",
    description: "Sarah-James-David trio achieves 91 vs 77 victory against Fujitsu UK using reputation leverage tactics. This win establishes the golden team pattern",
    participants: ["Sarah Mitchell", "James Chen", "David Armstrong", "Lisa Wong", "Robert Taylor"],
    impact: "positive",
    chemistryScore: 95,
    relatedProjectId: "h2h_006",
  },
  {
    id: "timeline_004",
    date: "2024-09-30",
    eventType: "project_loss",
    title: "BAE Systems Cybersecurity Loss - Critical Learning",
    description: "Lost Home Office bid 81 vs 94 against BAE Systems. Team learns to avoid direct competition in defense/intelligence sectors. Michael Roberts' strategic approach questioned",
    participants: ["Michael Roberts", "James Chen", "Emma Thompson"],
    impact: "negative",
    chemistryScore: 72,
    relatedProjectId: "h2h_004",
  },
  {
    id: "timeline_005",
    date: "2024-10-05",
    eventType: "project_loss",
    title: "Capita ERP Loss - Incumbent Advantage Identified",
    description: "Narrow 84 vs 86 loss to Capita at Cabinet Office. Team identifies incumbent relationships as critical factor, refines displacement strategies",
    participants: ["Michael Roberts", "James Chen", "Emma Thompson"],
    impact: "negative",
    chemistryScore: 75,
    relatedProjectId: "h2h_010",
  },
  {
    id: "timeline_006",
    date: "2024-10-22",
    eventType: "project_loss",
    title: "Fujitsu Cloud Migration Loss",
    description: "Lost to Fujitsu UK 78 vs 85 at Manchester Council. Underestimated legacy system integration advantage. Michael Roberts partnership struggles continue",
    participants: ["Michael Roberts", "Priya Patel", "Emma Thompson"],
    impact: "negative",
    chemistryScore: 68,
    relatedProjectId: "h2h_002",
  },
  {
    id: "timeline_007",
    date: "2024-11-01",
    eventType: "chemistry_change",
    title: "Sarah-James Chemistry Strengthens",
    description: "After 3 collaborations, Sarah Mitchell and James Chen chemistry score increases from 82 to 89 as they develop intuitive communication patterns",
    participants: ["Sarah Mitchell", "James Chen"],
    impact: "positive",
    chemistryScore: 89,
  },
  {
    id: "timeline_008",
    date: "2024-11-15",
    eventType: "project_win",
    title: "NHS Digital Transformation Victory",
    description: "Sarah-James-Emma-Robert-Lisa team wins 89 vs 82 against Capita using quality guarantees and innovation focus. First major healthcare sector win",
    participants: ["Sarah Mitchell", "James Chen", "Emma Thompson", "Robert Taylor", "Lisa Wong"],
    impact: "positive",
    chemistryScore: 91,
    relatedProjectId: "h2h_001",
  },
  {
    id: "timeline_009",
    date: "2024-11-28",
    eventType: "project_win",
    title: "Justice System Win - CGI Defeated",
    description: "Sarah-James-Emma win 88 vs 84 against CGI IT UK. Innovation-focused approach proves effective against traditional systems integrators",
    participants: ["Sarah Mitchell", "James Chen", "Emma Thompson"],
    impact: "positive",
    chemistryScore: 88,
    relatedProjectId: "h2h_007",
  },
  {
    id: "timeline_010",
    date: "2024-12-08",
    eventType: "project_win",
    title: "Education Platform Win - Perfect Chemistry",
    description: "Sarah-James-David-Robert team achieves 92 vs 79 victory against Sopra Steria. 13-point margin demonstrates perfect team chemistry and AI-powered innovation messaging",
    participants: ["Sarah Mitchell", "James Chen", "David Armstrong", "Robert Taylor"],
    impact: "positive",
    chemistryScore: 96,
    relatedProjectId: "h2h_003",
  },
  {
    id: "timeline_011",
    date: "2024-12-20",
    eventType: "project_win",
    title: "Healthcare Analytics Win - Sopra Dominated",
    description: "Second consecutive win against Sopra Steria (90 vs 81). Sarah-James-Emma-Robert-Lisa team establishes healthcare dominance",
    participants: ["Sarah Mitchell", "James Chen", "Emma Thompson", "Robert Taylor", "Lisa Wong"],
    impact: "positive",
    chemistryScore: 93,
    relatedProjectId: "h2h_009",
  },
  {
    id: "timeline_012",
    date: "2025-01-01",
    eventType: "achievement",
    title: "Q4 2024 Performance Review - 75% Win Rate",
    description: "Team achieves 75% win rate in Q4 with 6 wins and 2 losses. Sarah-James pairing reaches 85% win rate. Michael Roberts placed on performance improvement plan",
    participants: ["Sarah Mitchell", "James Chen", "David Armstrong", "Emma Thompson", "Priya Patel", "Lisa Wong", "Robert Taylor"],
    impact: "positive",
    chemistryScore: 90,
  },
  {
    id: "timeline_013",
    date: "2025-01-14",
    eventType: "project_win",
    title: "Smart City IoT Win - Sarah-Priya Success",
    description: "Sarah-Priya-David-Robert team wins 87 vs 83 against CGI. First perfect collaboration for Sarah-Priya pairing, establishing new winning pattern",
    participants: ["Sarah Mitchell", "Priya Patel", "David Armstrong", "Robert Taylor"],
    impact: "positive",
    chemistryScore: 92,
    relatedProjectId: "h2h_005",
  },
  {
    id: "timeline_014",
    date: "2025-02-05",
    eventType: "project_win",
    title: "Digital Workplace Win vs Atos - Stability Message",
    description: "Sarah-Priya-David-Robert team wins 86 vs 74 using financial stability messaging against troubled Atos UK. Establishes new competitive tactic",
    participants: ["Sarah Mitchell", "Priya Patel", "David Armstrong", "Robert Taylor"],
    impact: "positive",
    chemistryScore: 91,
    relatedProjectId: "h2h_008",
  },
  {
    id: "timeline_015",
    date: "2025-02-15",
    eventType: "partnership_formed",
    title: "David-Robert Perfect Partnership Recognized",
    description: "After 4 consecutive wins together, David Armstrong and Robert Taylor achieve 100% win rate as BW-Pricing pairing. Chemistry score reaches 94",
    participants: ["David Armstrong", "Robert Taylor"],
    impact: "positive",
    chemistryScore: 94,
  },
  {
    id: "timeline_016",
    date: "2025-03-01",
    eventType: "role_change",
    title: "Michael Roberts Moved to Business Development",
    description: "After 0% win rate in PM role, Michael Roberts transitions to BD role. Team restructure allows focus on proven winning combinations",
    participants: ["Michael Roberts"],
    impact: "neutral",
    chemistryScore: 85,
  },
];

export const MOCK_CRITICAL_MOMENTS: CriticalMoment[] = [
  {
    id: "moment_001",
    date: "2024-06-15",
    momentType: "new_hire",
    title: "David Armstrong Hired - Game Changer",
    description: "David Armstrong joins with 14 years bid writing experience, immediately elevating messaging quality and bringing 100% win rate across all partnerships",
    teamMembersAffected: ["David Armstrong"],
    impact: "high",
    beforeMetrics: { winRate: 62, chemistry: 75 },
    afterMetrics: { winRate: 85, chemistry: 92 },
    consequences: [
      "Perfect 4-0 win record in all David Armstrong collaborations",
      "Average scoring improvement of +9.5 points when David participates",
      "Established three 100% win rate partnerships (Sarah-David, James-David, David-Robert)",
      "Strategic messaging quality increased by 35% based on evaluator feedback",
    ],
  },
  {
    id: "moment_002",
    date: "2024-08-19",
    momentType: "major_win",
    title: "Transport for London Victory - Reputation Leverage Tactic Born",
    description: "91 vs 77 win against Fujitsu UK establishes reputation leverage as 100% win rate tactic. Sarah-James-David trio identified as optimal team pattern",
    teamMembersAffected: ["Sarah Mitchell", "James Chen", "David Armstrong"],
    impact: "high",
    beforeMetrics: { winRate: 65, chemistry: 82 },
    afterMetrics: { winRate: 78, chemistry: 95 },
    consequences: [
      "Reputation leverage tactic replicated 3 times with 100% success rate",
      "Sarah-James-David trio becomes default team for high-stakes bids",
      "14-point average margin when using reputation leverage",
      "Established trust-sensitive sector specialization (healthcare, citizen-facing)",
    ],
  },
  {
    id: "moment_003",
    date: "2024-09-30",
    momentType: "major_loss",
    title: "BAE Systems Loss - Strategic Pivot Point",
    description: "81 vs 94 loss in defense sector reveals futility of competing directly with BAE Systems. Team adopts partnership-first approach for defense/intelligence",
    teamMembersAffected: ["Michael Roberts", "James Chen", "Emma Thompson"],
    impact: "high",
    beforeMetrics: { winRate: 70, chemistry: 78 },
    afterMetrics: { winRate: 68, chemistry: 72 },
    consequences: [
      "Stopped bidding directly against BAE in defense/intelligence sectors",
      "Pursued 3 partnership opportunities worth £50M+ total",
      "Reallocated team resources to commercial sectors (95% win rate)",
      "Michael Roberts' PM effectiveness questioned, triggering performance review",
    ],
  },
  {
    id: "moment_004",
    date: "2024-11-01",
    momentType: "partnership_formed",
    title: "Sarah-James Perfect Chemistry Achieved",
    description: "After 3 successful collaborations, Sarah Mitchell and James Chen chemistry reaches 89/100, establishing the team's most reliable partnership",
    teamMembersAffected: ["Sarah Mitchell", "James Chen"],
    impact: "high",
    beforeMetrics: { winRate: 75, chemistry: 82 },
    afterMetrics: { winRate: 83, chemistry: 89 },
    consequences: [
      "83.3% win rate across 6 collaborations (5 wins, 1 loss)",
      "Average combined scoring advantage of +7.8 points",
      "Became go-to pairing for technically complex healthcare and infrastructure bids",
      "Set standard for PM-TL collaboration best practices",
    ],
  },
  {
    id: "moment_005",
    date: "2024-12-08",
    momentType: "major_win",
    title: "Education Platform Win - Peak Performance",
    description: "92 vs 79 victory (13-point margin) demonstrates peak team performance. Innovation-focused messaging combined with perfect team chemistry",
    teamMembersAffected: ["Sarah Mitchell", "James Chen", "David Armstrong", "Robert Taylor"],
    impact: "high",
    beforeMetrics: { winRate: 80, chemistry: 90 },
    afterMetrics: { winRate: 85, chemistry: 96 },
    consequences: [
      "Largest winning margin (13 points) in tracked history",
      "AI-powered innovation messaging became standard approach",
      "Sarah-James-David-Robert quartet identified as 'dream team'",
      "Education sector win rate increased to 100% (2/2)",
    ],
  },
  {
    id: "moment_006",
    date: "2025-03-01",
    momentType: "team_restructure",
    title: "Michael Roberts Role Change - Team Optimization",
    description: "After 0% PM win rate across 5 bids, Michael Roberts moves to Business Development role, allowing focus on proven winning team combinations",
    teamMembersAffected: ["Michael Roberts", "Sarah Mitchell", "Priya Patel"],
    impact: "medium",
    beforeMetrics: { winRate: 68, chemistry: 70 },
    afterMetrics: { winRate: 75, chemistry: 88 },
    consequences: [
      "Overall team win rate increased from 68% to 75%",
      "Sarah Mitchell became sole PM for all major bids",
      "Team chemistry improved from 70 to 88 with clearer role definitions",
      "Michael Roberts excels in BD, securing 5 qualified opportunities in first month",
    ],
  },
];

export const MOCK_FUTURE_FORECASTS: FutureCollaborationForecast[] = [
  {
    id: "forecast_001",
    partnership: { member1: "Priya Patel", member2: "Lisa Wong", role1: "Technical Lead", role2: "Subject Matter Expert" },
    projectedChemistry: 94,
    confidence: 87,
    reasoning: [
      "Both have perfect 100% win rates in healthcare sector",
      "Priya's data analytics expertise complements Lisa's clinical systems knowledge",
      "No historical collaboration yet - high potential for synergy",
      "Similar work styles and collaborative approaches based on network analysis",
    ],
    recommendedStartDate: "2025-04-01",
    expectedImpact: "Projected to create unstoppable healthcare bid team with 95%+ win rate when paired with Sarah Mitchell",
    optimalSectors: ["Healthcare IT", "NHS Digital Transformation", "Clinical Data Analytics"],
    riskFactors: ["Limited prior collaboration history", "Both have high workload - availability constraints"],
  },
  {
    id: "forecast_002",
    partnership: { member1: "Emma Thompson", member2: "Lisa Wong", role1: "Bid Writer", role2: "Subject Matter Expert" },
    projectedChemistry: 91,
    confidence: 92,
    reasoning: [
      "Already have 2 successful collaborations (100% win rate, 89.5 avg score)",
      "Emma's compliance expertise pairs well with Lisa's NHS frameworks knowledge",
      "Good chemistry (not excellent yet) suggests room for growth to excellent",
      "Both are methodical and detail-oriented based on collaboration patterns",
    ],
    recommendedStartDate: "2025-03-15",
    expectedImpact: "Increase Emma Thompson's healthcare win rate from 66% to 85%+ through Lisa's SME support",
    optimalSectors: ["Healthcare Compliance", "NHS Procurement", "Medical Records Systems"],
    riskFactors: ["Emma has lower overall win rate (66.7%) - needs confidence building"],
  },
  {
    id: "forecast_003",
    partnership: { member1: "James Chen", member2: "Priya Patel", role1: "Technical Lead", role2: "Technical Lead" },
    projectedChemistry: 88,
    confidence: 79,
    reasoning: [
      "Both are technical leads with complementary expertise (Cloud/AI vs Data/ML)",
      "No historical collaboration - moderate uncertainty",
      "Could create powerful dual-TL approach for complex infrastructure bids",
      "Both have high centrality scores (92 and 75) indicating collaboration strength",
    ],
    recommendedStartDate: "2025-05-01",
    expectedImpact: "Enable bidding on mega-projects (£10M+) requiring dual technical leadership with projected 80% win rate",
    optimalSectors: ["Large-scale Infrastructure", "AI/ML + Cloud Integration", "Smart Cities"],
    riskFactors: ["No precedent for dual-TL structure", "Potential role overlap creating confusion", "Both strong personalities - leadership dynamics uncertain"],
  },
  {
    id: "forecast_004",
    partnership: { member1: "Robert Taylor", member2: "Priya Patel", role1: "Pricing Specialist", role2: "Technical Lead" },
    projectedChemistry: 89,
    confidence: 88,
    reasoning: [
      "Already have 2 successful collaborations (100% win rate, 86.5 avg score)",
      "Robert's cost modeling + Priya's data analytics = data-driven pricing strategy",
      "Good chemistry with potential to become excellent",
      "Both are analytical and metrics-focused",
    ],
    recommendedStartDate: "2025-03-20",
    expectedImpact: "Develop AI-powered pricing models reducing bid prep time by 40% while increasing commercial competitiveness",
    optimalSectors: ["Data Analytics Projects", "IoT Platforms", "Performance-based Contracts"],
    riskFactors: ["Limited collaboration history (only 2 projects)"],
  },
  {
    id: "forecast_005",
    partnership: { member1: "Sarah Mitchell", member2: "Robert Taylor", role1: "Project Manager", role2: "Pricing Specialist" },
    projectedChemistry: 90,
    confidence: 93,
    reasoning: [
      "Already have 5 successful collaborations (80% win rate, 87.0 avg score)",
      "Good chemistry trending toward excellent",
      "Sarah's delivery focus + Robert's value engineering = compelling value propositions",
      "Historical data shows stronger performance when paired together vs separately",
    ],
    recommendedStartDate: "2025-04-10",
    expectedImpact: "Increase win rate from 80% to 90%+ by optimizing commercial strategy and delivery confidence messaging",
    optimalSectors: ["Value-driven Procurement", "Cost-sensitive Local Government", "Multi-year Contracts"],
    riskFactors: ["One notable loss (Cabinet Office ERP) - incumbent advantage factor"],
  },
];

export const MOCK_WINLOSS_INSIGHTS: WinLossInsight[] = [
  {
    id: "wl_001",
    category: "success_pattern",
    title: "Innovation-Led Positioning Delivers Consistent Wins",
    insight: "When you lead with innovation-focused messaging (AI, cloud-native, modern architecture), you achieve an 85.7% win rate with an average 8.2-point scoring advantage.",
    supportingData: "7 competitions using Innovation Focus: 6 wins, 1 loss. Particularly effective against CGI IT UK (2/2) and Sopra Steria (2/2).",
    actionable: "Prioritize innovation differentiation in all proposals. Develop reusable innovation modules: AI-powered analytics, cloud-native architecture templates, DevOps automation showcases.",
    confidence: 94,
    impact: "high",
  },
  {
    id: "wl_002",
    category: "success_pattern",
    title: "Reputation Leverage Against Fujitsu Shows Perfect Track Record",
    insight: "Tactfully highlighting Fujitsu's Post Office Horizon scandal in trust-sensitive contexts (healthcare, citizen-facing) produces 100% win rate with 12.3-point average advantage.",
    supportingData: "3 competitions using Reputation Leverage against Fujitsu: 3 wins, 0 losses. Transport for London win scored 91 vs their 77 (14-point gap).",
    actionable: "Systematically target Fujitsu opportunities in healthcare, justice, and citizen-facing sectors. Develop messaging emphasizing transparency, independent audits, and ethical business practices.",
    confidence: 96,
    impact: "high",
  },
  {
    id: "wl_003",
    category: "failure_pattern",
    title: "Competitive Pricing Alone Is Ineffective Strategy",
    insight: "Pure pricing competition yields only 25% win rate with average -2.1 point scoring impact. This tactic consistently fails against established incumbents.",
    supportingData: "4 competitions using Competitive Pricing as primary tactic: 1 win, 3 losses. Lost to Fujitsu UK despite competitive pricing when they had infrastructure advantage.",
    actionable: "Abandon price-led strategies. Shift to value proposition messaging: total cost of ownership, faster ROI, delivery confidence. Price competitively but never lead with it.",
    confidence: 91,
    impact: "high",
  },
  {
    id: "wl_004",
    category: "failure_pattern",
    title: "Head-to-Head with BAE Systems in Defense/Security Is Futile",
    insight: "Direct competition with BAE Systems in their core verticals (defense, cybersecurity, intelligence) resulted in 0% win rate and -13 point average deficit.",
    supportingData: "Home Office Cybersecurity bid: scored 81 vs BAE's 94. Their security clearance levels, defense heritage, and premium positioning are insurmountable advantages.",
    actionable: "Never bid directly against BAE in defense/intelligence sectors. Instead, pursue partnership/subcontractor approach or focus on commercial and non-security government work where they have limited presence.",
    confidence: 98,
    impact: "high",
  },
  {
    id: "wl_005",
    category: "success_pattern",
    title: "Financial Stability Messaging Devastates Troubled Competitors",
    insight: "Emphasizing long-term stability and UK commitment against Atos UK (parent company troubles) achieved 100% win rate with 12-point advantage.",
    supportingData: "Scottish Government Digital Workplace: scored 86 vs Atos 74. Stability messaging resonated strongly with procurement team concerned about supplier continuity.",
    actionable: "Monitor competitor financial health continuously. When rivals show instability (restructuring, parent company issues, falling margins), aggressively target their accounts with stability-focused messaging.",
    confidence: 87,
    impact: "medium",
  },
  {
    id: "wl_006",
    category: "opportunity",
    title: "Perfect Record Against Sopra Steria Reveals Systematic Weakness",
    insight: "You've achieved 100% win rate (2/2) against Sopra Steria with average 10.5-point margin. Their low win rate (57.1%) and high discounting (12.3%) signal desperation.",
    supportingData: "Education Platform: 92 vs 79. Healthcare Analytics: 90 vs 81. Value proposition and faster delivery consistently beat their price-led approach.",
    actionable: "Actively seek out all Sopra Steria opportunities in healthcare and education sectors. Lead with value over price, emphasize delivery confidence (68% vs 57% win rate), showcase faster timelines.",
    confidence: 93,
    impact: "medium",
  },
  {
    id: "wl_007",
    category: "warning",
    title: "Incumbent Advantage Can Override Quality Differentiation",
    insight: "Lost Cabinet Office ERP despite strong quality positioning because Capita held existing relationships. 84 vs 86 score shows you were competitive, but incumbency was decisive.",
    supportingData: "Only 2-point gap in close competition. Post-bid debrief confirmed existing relationships and change management concerns favored incumbent despite your technical superiority.",
    actionable: "When facing incumbents, develop specific displacement strategies: highlight their delivery failures, offer seamless transition plans, provide change management support, identify contract pain points through stakeholder research.",
    confidence: 89,
    impact: "medium",
  },
  {
    id: "wl_008",
    category: "opportunity",
    title: "Perfect Record Against CGI Through Innovation Differentiation",
    insight: "100% win rate (2/2) against CGI IT UK by positioning modern architecture against their traditional systems integration approach. Average 4.5-point margin.",
    supportingData: "Smart City IoT: 87 vs 83. Justice System: 88 vs 84. Their generic positioning and legacy SI model create clear differentiation opportunity.",
    actionable: "Target CGI opportunities in systems integration bids. Lead with AI automation, cloud-native architecture, DevOps delivery, and strategic partnership positioning vs transactional service provider.",
    confidence: 90,
    impact: "medium",
  },
];
